- hosts: "{{ target }}"
  vars:
    lsb: stretch
    rkt_url: https://github.com/rkt/rkt/releases/download/v1.29.0/rkt_1.29.0-1_amd64.deb
  tasks:
    - hostname:
        name: "{{ inventory_hostname }}"
      become: true

    - name: create systemd units directory
      file:
        path: /etc/usr/systemd/system
        owner: root
        group: root
        mode: 0755
        state: directory
      become: true

    - name: 127.0.0.1 in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1' 
        insertbefore: BOF
        line: "127.0.0.1\tlocalhost {{ inventory_hostname }} {{ inventory_hostname_short }}"
      become: true

    - name: 127.0.1.1 in /etc/hosts
      lineinfile:
        path: /etc/hosts
        insertafter: '^127\.0\.0\.1'
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1\tlocalhost {{ inventory_hostname }} {{ inventory_hostname_short }}"
      become: true

    - name: ::1 in /etc/hosts
      lineinfile:
        path: /etc/hosts
        insertafter: '127\.0\.1\.1'
        regexp: '^::1'
        line: "::1\tlocalhost {{ inventory_hostname }} {{ inventory_hostname_short }}"
      become: true

    - name: install packages
      apt:
        name: "{{ item }}"
      items:
        - apt-transport-https
        - aptitude
        - exim4
        - ntp
        - python-pip
      become: true

    - name: set timezone to Europe/Berlin
      timezone:
        name: Europe/Berlin
      become: true

    - name: generate en_US.UTF-8
      debconf:
        name: locales
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
      with_items:
        - question: locales/locales_to_be_generated
          value: en_US.UTF-8 UTF-8
          vtype: multiselect
        - question: locales/default_environment_locale
          value: en_US.UTF-8
          vtype: select
      become: true

    - name: configure exim4 to SMTP
      debconf:
        name: exim4-config
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
      with_items:
        - question: exim4/dc_eximconfig_configtype
          value: internet site; mail is sent and received directly using SMTP
          vtype: select
        - question: exim4/mailname
          value: "{{ inventory_hostname }}"
          vtype: string
        - question: exim4/dc_local_interfaces
          value: 127.0.0.1 ; ::1
          vtype: string
        - question: exim4/dc_other_hostnames
          value: ""
          vtype: string
        - question: exim4/dc_relay_domains
          value: ""
          vtype: string
        - question: exim4/dc_relay_nets
          value: ""
          vtype: string
        - question: exim4/dc_localdelivery
          value: mbox format in /var/mail/
          vtype: select
      become: true
      register: exim

    - name: remove exim config files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/exim4/update-exim4.conf.conf"
        - "/etc/mailname"
      become: true
      when: exim.changed

    - name: reconfigure package exim4-config
      command: "dpkg-reconfigure -fnoninteractive exim4-config"
      become: true
      when: exim.changed

    - name: add docker apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      become: true

    - name: add docker repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian\t{{ lsb }}\tstable"
        filename: docker
      become: true

    - name: install docker
      apt:
        name: docker-ce
      become: true

    - name: install docker-py for ansible
      pip:
        name: docker-py
        state: latest
      become: true

    - name: install rkt
      apt:
        deb: "{{ rkt_url }}"
      become: true

    - name: rkt gc
      cron:
        name: rkt gc
        special_time: daily
        job: /usr/bin/rkt image gc
      become: true

    - name: add to docker & rkt group
      user:
        name: googol
        groups: docker, rkt
        append: yes
      become: true

    - name: update
      apt:
        update_cache: yes
        upgrade: full
        autoclean: yes
        autoremove: yes
      become: true

    - name: prune docker
      command: docker system prune -a -f
      become: true
