---
- hosts: transmission
  vars:
    rpc_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      63396264346236316662663239316631323139386635653530393561363931363637656434616566
      6332643364623730363661366566633338616539326138330a336565653565333864383839326436
      33623238653034343165343362323961316462353038646237623634396434313232633632326563
      3236646435623036610a343033356666613632646534316336386533306435393835663334336666
      32643561316365653535653430356633663736653334613134396131316439343764363665356532
      34343430363366323262386266393433383935396634626639653261383337613036376535376138
      663962313962326663363330626366663934
  tasks:
    - name: pull images
      docker_image:
        name: "{{ item }}"
        force: yes
      with_items:
        - googollee/dnsdock
        - googollee/nginx
        - googollee/transmission

    - name: mkdirs
      file:
        path: "{{ item }}"
        owner: googol
        group: googol
        mode: 0755
        state: directory
      with_items:
        - ~/dl
        - ~/transmission
        - ~/transmission/downloads

    - name: mk link
      file:
        path: ~/torrents
        src: ~/transmission/downloads
        owner: googol
        group: googol
        mode: 0755
        state: link

    - name: generate check file
      file:
        path: ~/dl/.check
        content: ""
        state: touch
        owner: googol
        group: googol
        mode: 0644

    - name: add dnsdock service
      copy:
        dest: /usr/lib/systemd/system/dnsdock.service
        content: |
          [Unit]
          Description=DNS for docker
          After=docker.service
          Requires=docker.service

          [Service]
          TimeoutStartSec=0
          Restart=always
          RestartSec=3
          ExecStartPre=-/usr/bin/docker rm dnsdock
          ExecStart=/usr/bin/docker run --rm --name dnsdock \
            -p 172.17.0.1:53:53/udp \
            -v /var/run/docker.sock:/var/run/docker.sock \
            googollee/dnsdock

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: 0644
      become: true

    - name: add nginx service
      copy:
        dest: /usr/lib/systemd/system/nginx.service
        content: |
          [Unit]
          Description=Webserver frontend nginx
          After=docker.service dnsdock.service
          Requires=docker.service dnsdock.service

          [Service]
          TimeoutStartSec=0
          Restart=always
          RestartSec=3
          ExecStartPre=-/usr/bin/docker rm nginx
          ExecStart=/usr/bin/docker run --rm --dns 172.17.0.1 --name nginx \
            -p 80:80 -p 443:443 \
            -v /home/googol/dl:/var/www/dl \
            googollee/nginx

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: 0644
      become: true

    - name: add transmission service
      copy:
        dest: /usr/lib/systemd/system/transmission.service
        content: |
          [Unit]
          Description=transmission
          After=docker.service dnsdock.service
          Requires=docker.service dnsdock.service nginx.service

          [Service]
          TimeoutStartSec=0
          Restart=always
          RestartSec=3
          ExecStartPre=-/usr/bin/docker rm transmission
          ExecStart=/usr/bin/docker run --dns 172.17.0.1 --rm --name transmission \
            --env RPC_PASSWORD="{{ rpc_password }}" \
            -p 51413:51413 -p 8888:80 \
            -v /home/googol/transmission:/var/lib/transmission \
            googollee/transmission

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: 0644
      become: true

    - name: enable services
      systemd:
        name: "{{ item }}"
        daemon_reload: yes
        enabled: yes
        state: restarted
      with_items:
        - dnsdock
        - nginx
        - transmission
      become: true
