---
- hosts: transmission
  vars:
  tasks:
    - name: pull images
      docker_image:
        name: "{{ item }}"
        source: pull
        force_source: yes
      with_items:
        - googollee/frontend
        - googollee/filehost
        - googollee/transmission
        - googollee/vote

    - name: mkdirs
      file:
        path: "{{ item }}"
        owner: googol
        group: googol
        mode: 0755
        state: directory
      with_items:
        - ~/dl
        - ~/transmission
        - ~/transmission/downloads

    - name: mk link
      file:
        path: ~/torrents
        src: ~/transmission/downloads
        owner: googol
        group: googol
        mode: 0755
        state: link

    - name: generate check file
      file:
        path: ~/dl/.check
        content: ""
        state: touch
        owner: googol
        group: googol
        mode: 0644

    - name: add frontend service
      copy:
        dest: /usr/lib/systemd/system/frontend.service
        content: |
          [Unit]
          Description=Frontend
          After=docker.service
          Requires=docker.service

          [Service]
          TimeoutStartSec=0
          Restart=always
          RestartSec=3
          ExecStartPre=-/usr/bin/docker rm frontend
          ExecStart=/usr/bin/docker run --rm --name frontend \
            -p 80:80 -p 443:443 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --label "traefik.frontend.rule=Host:admin.googol.im" \
            googollee/frontend

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: 0644
      become: true

    - name: add file host service
      copy:
        dest: /usr/lib/systemd/system/filehost.service
        content: |
          [Unit]
          Description=File host
          After=docker.service
          Requires=docker.service

          [Service]
          TimeoutStartSec=0
          Restart=always
          RestartSec=3
          ExecStartPre=-/usr/bin/docker rm filehost
          ExecStart=/usr/bin/docker run --rm --name filehost \
            -v /home/googol/dl:/var/www/dl \
            --label "traefik.frontend.rule=Host:dl.googol.im" \
            googollee/filehost

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: 0644
      become: true

    - name: add transmission service
      copy:
        dest: /usr/lib/systemd/system/transmission.service
        content: |
          [Unit]
          Description=transmission
          After=docker.service
          Requires=docker.service

          [Service]
          TimeoutStartSec=0
          Restart=always
          RestartSec=3
          ExecStartPre=-/usr/bin/docker rm transmission
          ExecStart=/usr/bin/docker run --rm --name transmission \
            -p 51413:51413 -p 51413:51413/udp \
            -v /home/googol/transmission:/var/lib/transmission \
            --label "traefik.frontend.rule=Host:transmission.googol.im" \
            googollee/transmission

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: 0644
      become: true

    - name: add vote service
      copy:
        dest: /usr/lib/systemd/system/vote.service
        content: |
          [Unit]
          Description=vote
          After=docker.service
          Requires=docker.service

          [Service]
          TimeoutStartSec=0
          Restart=always
          RestartSec=3
          ExecStartPre=-/usr/bin/docker rm vote
          ExecStart=/usr/bin/docker run --rm --name vote \
            --label "traefik.frontend.rule=Host:vote.googol.im" \
            googollee/vote

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: 0644
      become: true

    - name: enable services
      systemd:
        name: "{{ item }}"
        daemon_reload: yes
        enabled: yes
        state: restarted
      with_items:
        - frontend
        - filehost
        - transmission
        - vote
      become: true
