---

- name: pull dnsdock
  docker_image:
    name: googollee/dnsdock
    force: yes

- name: mkdir /usr/lib/systemd/system
  file: path=/usr/lib/systemd/system state=directory
  become: yes

- name: register dnsdock service
  copy:
    src: dnsdock.service
    dest: /usr/lib/systemd/system/
  become: yes

- name: launch dnsdock
  systemd:
    daemon_reload: yes
    name: dnsdock.service
    enabled: yes
    state: restarted
  become: yes
