---

- name: pull nginx
  docker_image:
    name: googollee/nginx
    force: yes

- name: create dl
  file:
    path: ~/dl
    mode: 0755
    state: directory

- name: register nginx service
  copy:
    src: nginx.service
    dest: /usr/lib/systemd/system/
  become: yes

- name: launch nginx
  systemd:
    daemon_reload: yes
    name: nginx.service
    enabled: yes
    state: restarted
  become: yes
