---

- name: be sure Docker is installed
  apt:
    name: docker-ce
    state: latest
  become: yes
  ignore_errors: yes
  register: docker_exist

- name: let apt support https
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - apt-transport-https
    - python-setuptools
  become: yes
  when: docker_exist | failed

- name: install pip
  command: easy_install pip
  become: yes
  when: docker_exist | failed

- name: install docker key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: yes
  when: docker_exist | failed

- name: create docker-ce repo
  command: bash -c 'echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker-ce.list'
  become: yes
  when: docker_exist | failed

- name: install docker python module
  pip:
    name: "docker-compose"
    state: latest
  become: yes
  when: docker_exist | failed

- name: be sure Docker is installed
  apt:
    name: docker-ce
    update_cache: yes
    state: latest
  become: yes
  when: docker_exist | failed

- name: add googol to docker group
  user:
    name: googol
    groups: docker
    append: yes
  become: yes
  register: add_group
  when: docker_exist | failed
